# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170719_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pubDate',
            field=models.CharField(default=datetime.datetime(2017, 7, 21, 20, 26, 49, 103311, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
