# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_negativetraining_neutraltraining_positivetraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='stemmedVerbNegativeTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(default=0, unique=True)),
                ('stemmedVerb', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='stemmedVerbNeutralTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(default=0, unique=True)),
                ('stemmedVerb', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='stemmedVerbPositiveTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(default=0, unique=True)),
                ('stemmedVerb', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stemmedVerbTestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(default=0, unique=True)),
                ('stemmedVerb', models.CharField(max_length=500)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Article')),
            ],
        ),
    ]
