# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_stemmedverbnegativetraining_stemmedverbneutraltraining_stemmedverbpositivetraining_stemmedverbtestne'),
    ]

    operations = [
        migrations.CreateModel(
            name='testNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(default=0, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
