# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_testnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stemmedverbtestnews',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.testNews'),
        ),
        migrations.AlterField(
            model_name='testnews',
            name='s_no',
            field=models.IntegerField(default=0),
        ),
    ]
