# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20170729_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stemmedverbtestnews',
            name='title',
        ),
    ]
