# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_stemmedverbtestnews_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='classifiedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Article')),
            ],
        ),
        migrations.CreateModel(
            name='newsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='classifiednews',
            name='news_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.newsType'),
        ),
    ]
