# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20170729_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testnews',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Article'),
        ),
    ]
