# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20170730_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testnews',
            old_name='title',
            new_name='article',
        ),
    ]
