# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20170730_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testnews',
            name='article',
        ),
        migrations.AddField(
            model_name='testnews',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
