# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_negativeclassified_neutralclassified_positiveclassified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stemmedverbpositivetraining',
            name='stemmedVerb',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
