# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_tfidfnegativeclassified_tfidfneutralclassified_tfidfpositiveclassified'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaiveCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('neutral', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TfidfCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('neutral', models.IntegerField()),
            ],
        ),
    ]
